### PR TITLE
Handle nullability properly on EventHandlerImpl

### LINKED ISSUE #17: Hiding channel causes app crash.
Hiding channel with clearing history causes app crash.

**SDK ver.** 4.2.11-beta-6
Code: `client.channel(channel.type, channel.id).hide(true)`
Debug details:

**Crashing code(SDK):**
EventHandlerImpl.kt
`is ChannelHiddenEvent -> {
                    val channelEntity = ChannelEntity(event.channel!!)`

`event.channel` is null at the moment of receiving event.

**Received event:**
`
event = {ChannelHiddenEvent@16844} "ChatEvent(type='channel.hidden')"
 channel = null
 cid = "messaging:!members-FJg6K2RrRM2l9i3ig_H8QgrSwhZOXCLPAGUStqjufcA"
 clearHistory = {Boolean@17122} false
 createdAt = {Date@17123} "Fri Jul 17 10:48:35 GMT+07:00 2020"
 member = null
 message = null
 reaction = null
 receivedAt = {Date@17124} "Fri Jul 17 10:48:36 GMT+07:00 2020"
 totalUnreadCount = null
 type = "channel.hidden"
 unreadChannels = null
 user = {User@17126} "User(id=ea7ce212-0ba2-4325-8e33-85e0453e49e9, role=user, invisible=false, banned=false, devices=[], online=true, createdAt=Wed Jul 08 09:32:03 GMT+07:00 2020, updatedAt=Fri Jul 17 10:47:57 GMT+07:00 2020, lastActive=Fri Jul 17 10:41:48 GMT+07:00 2020, totalUnreadCount=0, unreadChannels=0, unreadCount=0, mutes=[], teams=[], channelMutes=[], extraData={image=https://test/api/assets/7be02e9c-00d1-41be-a1d2-6c6b968f8184, name=Dmitrii2})"
 shadow$_klass_ = {Class@16386} "class io.getstream.chat.android.client.events.ChannelHiddenEvent"
 shadow$_monitor_ = 0
`

**Debug log:**
`
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.test, PID: 7245
    kotlin.KotlinNullPointerException
        at io.getstream.chat.android.livedata.EventHandlerImpl.updateOfflineStorageFromEvents$livedata_release(EventHandlerImpl.kt:107)
        at io.getstream.chat.android.livedata.EventHandlerImpl$updateOfflineStorageFromEvents$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
`

gz#4494

### PR DESCRIPTION
**Pull request by JcMinarro**
Acording with the [Event Object documentation](https://getstream.io/chat/docs/event_object/?language=js#event-object) Event's attributes are optionals. It force us to have null values on our event models and they aren't handled on the proper way.
We need to define a proper strcuture for our Events and then create our models with non-null values.
Until we have it defined, I have Null-Safe our code on `EventHandlerImpl`

Fix #17

### CODE REVIEW

**Comment by tschellenbach** [comment]
This fixes the NPE but results in the code doing the wrong thing. IE skipping the update.

It seems better to fail and have a clear error, rather than deal with data going out of sync and trying to figure out what caused that...

My 2 cents, your project though so feel free to proceed how you want.

**Comment by JcMinarro** [comment]
> This fixes the NPE but results in the code doing the wrong thing. IE skipping the update.
> 
> It seems better to fail and have a clear error, rather than deal with data going out of sync and trying to figure out what caused that...
> 
> My 2 cents, your project though so feel free to proceed how you want.

I like the Fail-Fast Principle, but on that case we can't follow it. It is not an error on our side, events structure is not defined and we don't know which attributes are going to be optionals. It could fail on a third-party dev App, crashing their Apps without any valid update on their side to fix the App.
If required attributes are not present in the event, the update is skipping, why do you think the code is doing the wrong thing?

**Comment by tschellenbach** [comment]
It's just that it changes the error report from:

Current: NPE in line 123 (easy to debug)

To: After hiding a channel, sometimes this channel still shows up in the UI. (hard to debug)

**Comment by tschellenbach** [comment]
On the other hand its indeed nice not to crash in case backend changes any
of these fields. (Dont think they will, but it's a nice safety)

**Pull request merged**
